rmin        =  1.0
form_factor =  1.0
zmax        = 10.0

field_file = "data/homogeneous_field.dat"

t_step = 1e-4

field_to_mm     = 1.0
field_to_Vpercm = 1000.0

field_invert_z = true

generator = { FixedPos = [0.0, 0.0, 9.0] }
